# GitHub Sponsors
github: [ziuus]

# Ko-fi
ko_fi: noelyt101

# Buy Me a Coffee
buy_me_a_coffee: ziuus

# Patreon
patreon: noelpaul

# Open Collective
open_collective: noelpaul

# Custom donation links
custom: ['https://github.com/sponsors/ziuus']