# These are supported funding model platforms

# patreon: your-patreon-username
# open_collective: your-collective-name
# ko_fi: your-ko-fi-username
# buy_me_a_coffee: your-buy-me-a-coffee-username

# Custom links (PayPal, Crypto, etc)
custom: ['https://paypal.me/your-paypal-username', 'https://your-crypto-wallet-link.com']
